# Generated by Django 5.2.5 on 2025-09-25 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionDetail', models.TextField()),
                ('contactList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contactlist')),
            ],
        ),
    ]
