# Generated by Django 5.2.6 on 2025-10-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_profile_point_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='actionDetail',
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='specfile',
            field=models.FileField(blank=True, upload_to='specfile'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='complete',
            field=models.CharField(),
        ),
        migrations.AddField(
            model_name='action',
            name='actiondetail',
            field=models.CharField(default='default'),
            preserve_default=False,
        ),
    ]
