# Generated by Django 5.2.6 on 2025-10-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_action_actiondetail_product_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specfile',
            field=models.FileField(blank=True, null=True, upload_to='specfile'),
        ),
    ]
